FROM golang:1.25.3-alpine3.22

RUN export GO111MODULE="on"

RUN go install github.com/githubnemo/CompileDaemon@latest

WORKDIR /app

COPY . /app

RUN go mod download

ENTRYPOINT CompileDaemon -polling --build="go build main.go" --command=./main
