// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Accesses       string
	Auths          string
	RolesUsers     string
	Sessions       string
	TokenPasswords string
	Users          string
}{
	Accesses:       "accesses",
	Auths:          "auths",
	RolesUsers:     "roles_users",
	Sessions:       "sessions",
	TokenPasswords: "token_passwords",
	Users:          "users",
}
