// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// TestToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestToOne(t *testing.T) {
	t.Run("AccessToSessionUsingIDSessionSession", testAccessToOneSessionUsingIDSessionSession)
	t.Run("AuthToUserUsingIDUserUser", testAuthToOneUserUsingIDUserUser)
	t.Run("RolesUserToUserUsingIDUserUser", testRolesUserToOneUserUsingIDUserUser)
	t.Run("SessionToAuthUsingIDAuthAuth", testSessionToOneAuthUsingIDAuthAuth)
	t.Run("TokenPasswordToUserUsingIDUserUser", testTokenPasswordToOneUserUsingIDUserUser)
}

// TestOneToOne tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOne(t *testing.T) {
	t.Run("UserToTokenPasswordUsingIDUserTokenPassword", testUserOneToOneTokenPasswordUsingIDUserTokenPassword)
}

// TestToMany tests cannot be run in parallel
// or deadlocks can occur.
func TestToMany(t *testing.T) {
	t.Run("AuthToIDAuthSessions", testAuthToManyIDAuthSessions)
	t.Run("SessionToIDSessionAccesses", testSessionToManyIDSessionAccesses)
	t.Run("UserToIDUserAuths", testUserToManyIDUserAuths)
	t.Run("UserToIDUserRolesUsers", testUserToManyIDUserRolesUsers)
}

// TestToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneSet(t *testing.T) {
	t.Run("AccessToSessionUsingIDSessionAccesses", testAccessToOneSetOpSessionUsingIDSessionSession)
	t.Run("AuthToUserUsingIDUserAuths", testAuthToOneSetOpUserUsingIDUserUser)
	t.Run("RolesUserToUserUsingIDUserRolesUsers", testRolesUserToOneSetOpUserUsingIDUserUser)
	t.Run("SessionToAuthUsingIDAuthSessions", testSessionToOneSetOpAuthUsingIDAuthAuth)
	t.Run("TokenPasswordToUserUsingIDUserTokenPassword", testTokenPasswordToOneSetOpUserUsingIDUserUser)
}

// TestToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToOneRemove(t *testing.T) {}

// TestOneToOneSet tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneSet(t *testing.T) {
	t.Run("UserToTokenPasswordUsingIDUserTokenPassword", testUserOneToOneSetOpTokenPasswordUsingIDUserTokenPassword)
}

// TestOneToOneRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestOneToOneRemove(t *testing.T) {}

// TestToManyAdd tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyAdd(t *testing.T) {
	t.Run("AuthToIDAuthSessions", testAuthToManyAddOpIDAuthSessions)
	t.Run("SessionToIDSessionAccesses", testSessionToManyAddOpIDSessionAccesses)
	t.Run("UserToIDUserAuths", testUserToManyAddOpIDUserAuths)
	t.Run("UserToIDUserRolesUsers", testUserToManyAddOpIDUserRolesUsers)
}

// TestToManySet tests cannot be run in parallel
// or deadlocks can occur.
func TestToManySet(t *testing.T) {}

// TestToManyRemove tests cannot be run in parallel
// or deadlocks can occur.
func TestToManyRemove(t *testing.T) {}
