// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

// This test suite runs each operation test in parallel.
// Example, if your database has 3 tables, the suite will run:
// table1, table2 and table3 Delete in parallel
// table1, table2 and table3 Insert in parallel, and so forth.
// It does NOT run each operation group in parallel.
// Separating the tests thusly grants avoidance of Postgres deadlocks.
func TestParent(t *testing.T) {
	t.Run("Accesses", testAccesses)
	t.Run("Auths", testAuths)
	t.Run("RolesUsers", testRolesUsers)
	t.Run("Sessions", testSessions)
	t.Run("TokenPasswords", testTokenPasswords)
	t.Run("Users", testUsers)
}

func TestDelete(t *testing.T) {
	t.Run("Accesses", testAccessesDelete)
	t.Run("Auths", testAuthsDelete)
	t.Run("RolesUsers", testRolesUsersDelete)
	t.Run("Sessions", testSessionsDelete)
	t.Run("TokenPasswords", testTokenPasswordsDelete)
	t.Run("Users", testUsersDelete)
}

func TestQueryDeleteAll(t *testing.T) {
	t.Run("Accesses", testAccessesQueryDeleteAll)
	t.Run("Auths", testAuthsQueryDeleteAll)
	t.Run("RolesUsers", testRolesUsersQueryDeleteAll)
	t.Run("Sessions", testSessionsQueryDeleteAll)
	t.Run("TokenPasswords", testTokenPasswordsQueryDeleteAll)
	t.Run("Users", testUsersQueryDeleteAll)
}

func TestSliceDeleteAll(t *testing.T) {
	t.Run("Accesses", testAccessesSliceDeleteAll)
	t.Run("Auths", testAuthsSliceDeleteAll)
	t.Run("RolesUsers", testRolesUsersSliceDeleteAll)
	t.Run("Sessions", testSessionsSliceDeleteAll)
	t.Run("TokenPasswords", testTokenPasswordsSliceDeleteAll)
	t.Run("Users", testUsersSliceDeleteAll)
}

func TestExists(t *testing.T) {
	t.Run("Accesses", testAccessesExists)
	t.Run("Auths", testAuthsExists)
	t.Run("RolesUsers", testRolesUsersExists)
	t.Run("Sessions", testSessionsExists)
	t.Run("TokenPasswords", testTokenPasswordsExists)
	t.Run("Users", testUsersExists)
}

func TestFind(t *testing.T) {
	t.Run("Accesses", testAccessesFind)
	t.Run("Auths", testAuthsFind)
	t.Run("RolesUsers", testRolesUsersFind)
	t.Run("Sessions", testSessionsFind)
	t.Run("TokenPasswords", testTokenPasswordsFind)
	t.Run("Users", testUsersFind)
}

func TestBind(t *testing.T) {
	t.Run("Accesses", testAccessesBind)
	t.Run("Auths", testAuthsBind)
	t.Run("RolesUsers", testRolesUsersBind)
	t.Run("Sessions", testSessionsBind)
	t.Run("TokenPasswords", testTokenPasswordsBind)
	t.Run("Users", testUsersBind)
}

func TestOne(t *testing.T) {
	t.Run("Accesses", testAccessesOne)
	t.Run("Auths", testAuthsOne)
	t.Run("RolesUsers", testRolesUsersOne)
	t.Run("Sessions", testSessionsOne)
	t.Run("TokenPasswords", testTokenPasswordsOne)
	t.Run("Users", testUsersOne)
}

func TestAll(t *testing.T) {
	t.Run("Accesses", testAccessesAll)
	t.Run("Auths", testAuthsAll)
	t.Run("RolesUsers", testRolesUsersAll)
	t.Run("Sessions", testSessionsAll)
	t.Run("TokenPasswords", testTokenPasswordsAll)
	t.Run("Users", testUsersAll)
}

func TestCount(t *testing.T) {
	t.Run("Accesses", testAccessesCount)
	t.Run("Auths", testAuthsCount)
	t.Run("RolesUsers", testRolesUsersCount)
	t.Run("Sessions", testSessionsCount)
	t.Run("TokenPasswords", testTokenPasswordsCount)
	t.Run("Users", testUsersCount)
}

func TestHooks(t *testing.T) {
	t.Run("Accesses", testAccessesHooks)
	t.Run("Auths", testAuthsHooks)
	t.Run("RolesUsers", testRolesUsersHooks)
	t.Run("Sessions", testSessionsHooks)
	t.Run("TokenPasswords", testTokenPasswordsHooks)
	t.Run("Users", testUsersHooks)
}

func TestInsert(t *testing.T) {
	t.Run("Accesses", testAccessesInsert)
	t.Run("Accesses", testAccessesInsertWhitelist)
	t.Run("Auths", testAuthsInsert)
	t.Run("Auths", testAuthsInsertWhitelist)
	t.Run("RolesUsers", testRolesUsersInsert)
	t.Run("RolesUsers", testRolesUsersInsertWhitelist)
	t.Run("Sessions", testSessionsInsert)
	t.Run("Sessions", testSessionsInsertWhitelist)
	t.Run("TokenPasswords", testTokenPasswordsInsert)
	t.Run("TokenPasswords", testTokenPasswordsInsertWhitelist)
	t.Run("Users", testUsersInsert)
	t.Run("Users", testUsersInsertWhitelist)
}

func TestReload(t *testing.T) {
	t.Run("Accesses", testAccessesReload)
	t.Run("Auths", testAuthsReload)
	t.Run("RolesUsers", testRolesUsersReload)
	t.Run("Sessions", testSessionsReload)
	t.Run("TokenPasswords", testTokenPasswordsReload)
	t.Run("Users", testUsersReload)
}

func TestReloadAll(t *testing.T) {
	t.Run("Accesses", testAccessesReloadAll)
	t.Run("Auths", testAuthsReloadAll)
	t.Run("RolesUsers", testRolesUsersReloadAll)
	t.Run("Sessions", testSessionsReloadAll)
	t.Run("TokenPasswords", testTokenPasswordsReloadAll)
	t.Run("Users", testUsersReloadAll)
}

func TestSelect(t *testing.T) {
	t.Run("Accesses", testAccessesSelect)
	t.Run("Auths", testAuthsSelect)
	t.Run("RolesUsers", testRolesUsersSelect)
	t.Run("Sessions", testSessionsSelect)
	t.Run("TokenPasswords", testTokenPasswordsSelect)
	t.Run("Users", testUsersSelect)
}

func TestUpdate(t *testing.T) {
	t.Run("Accesses", testAccessesUpdate)
	t.Run("Auths", testAuthsUpdate)
	t.Run("RolesUsers", testRolesUsersUpdate)
	t.Run("Sessions", testSessionsUpdate)
	t.Run("TokenPasswords", testTokenPasswordsUpdate)
	t.Run("Users", testUsersUpdate)
}

func TestSliceUpdateAll(t *testing.T) {
	t.Run("Accesses", testAccessesSliceUpdateAll)
	t.Run("Auths", testAuthsSliceUpdateAll)
	t.Run("RolesUsers", testRolesUsersSliceUpdateAll)
	t.Run("Sessions", testSessionsSliceUpdateAll)
	t.Run("TokenPasswords", testTokenPasswordsSliceUpdateAll)
	t.Run("Users", testUsersSliceUpdateAll)
}
