// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

func testDogsUpsert(t *testing.T) {
	t.Parallel()

	if len(dogAllColumns) == len(dogPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Dog{}
	if err = randomize.Struct(seed, &o, dogDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Dog: %s", err)
	}

	count, err := Dogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, dogDBTypes, false, dogPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Dog: %s", err)
	}

	count, err = Dogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDogs(t *testing.T) {
	t.Parallel()

	query := Dogs()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDogsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Dog{}
	if err = randomize.Struct(seed, o, dogDBTypes, true, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Dogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDogsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Dog{}
	if err = randomize.Struct(seed, o, dogDBTypes, true, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Dogs().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Dogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDogsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Dog{}
	if err = randomize.Struct(seed, o, dogDBTypes, true, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DogSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Dogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDogsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Dog{}
	if err = randomize.Struct(seed, o, dogDBTypes, true, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DogExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Dog exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DogExists to return true, but got false.")
	}
}

func testDogsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Dog{}
	if err = randomize.Struct(seed, o, dogDBTypes, true, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	dogFound, err := FindDog(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if dogFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDogsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Dog{}
	if err = randomize.Struct(seed, o, dogDBTypes, true, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Dogs().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDogsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Dog{}
	if err = randomize.Struct(seed, o, dogDBTypes, true, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Dogs().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDogsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	dogOne := &Dog{}
	dogTwo := &Dog{}
	if err = randomize.Struct(seed, dogOne, dogDBTypes, false, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}
	if err = randomize.Struct(seed, dogTwo, dogDBTypes, false, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = dogOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = dogTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Dogs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDogsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	dogOne := &Dog{}
	dogTwo := &Dog{}
	if err = randomize.Struct(seed, dogOne, dogDBTypes, false, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}
	if err = randomize.Struct(seed, dogTwo, dogDBTypes, false, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = dogOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = dogTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Dogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func dogBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *Dog) error {
	*o = Dog{}
	return nil
}

func dogAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *Dog) error {
	*o = Dog{}
	return nil
}

func dogAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *Dog) error {
	*o = Dog{}
	return nil
}

func dogBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Dog) error {
	*o = Dog{}
	return nil
}

func dogAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *Dog) error {
	*o = Dog{}
	return nil
}

func dogBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Dog) error {
	*o = Dog{}
	return nil
}

func dogAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *Dog) error {
	*o = Dog{}
	return nil
}

func dogBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Dog) error {
	*o = Dog{}
	return nil
}

func dogAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *Dog) error {
	*o = Dog{}
	return nil
}

func testDogsHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &Dog{}
	o := &Dog{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, dogDBTypes, false); err != nil {
		t.Errorf("Unable to randomize Dog object: %s", err)
	}

	AddDogHook(boil.BeforeInsertHook, dogBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	dogBeforeInsertHooks = []DogHook{}

	AddDogHook(boil.AfterInsertHook, dogAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	dogAfterInsertHooks = []DogHook{}

	AddDogHook(boil.AfterSelectHook, dogAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	dogAfterSelectHooks = []DogHook{}

	AddDogHook(boil.BeforeUpdateHook, dogBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	dogBeforeUpdateHooks = []DogHook{}

	AddDogHook(boil.AfterUpdateHook, dogAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	dogAfterUpdateHooks = []DogHook{}

	AddDogHook(boil.BeforeDeleteHook, dogBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	dogBeforeDeleteHooks = []DogHook{}

	AddDogHook(boil.AfterDeleteHook, dogAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	dogAfterDeleteHooks = []DogHook{}

	AddDogHook(boil.BeforeUpsertHook, dogBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	dogBeforeUpsertHooks = []DogHook{}

	AddDogHook(boil.AfterUpsertHook, dogAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	dogAfterUpsertHooks = []DogHook{}
}

func testDogsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Dog{}
	if err = randomize.Struct(seed, o, dogDBTypes, true, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Dogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDogsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Dog{}
	if err = randomize.Struct(seed, o, dogDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(dogColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Dogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDogsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Dog{}
	if err = randomize.Struct(seed, o, dogDBTypes, true, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDogsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Dog{}
	if err = randomize.Struct(seed, o, dogDBTypes, true, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DogSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDogsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Dog{}
	if err = randomize.Struct(seed, o, dogDBTypes, true, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Dogs().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	dogDBTypes = map[string]string{`ID`: `int8`, `Name`: `string`}
	_          = bytes.MinRead
)

func testDogsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(dogPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(dogAllColumns) == len(dogPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Dog{}
	if err = randomize.Struct(seed, o, dogDBTypes, true, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Dogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, dogDBTypes, true, dogPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDogsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(dogAllColumns) == len(dogPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Dog{}
	if err = randomize.Struct(seed, o, dogDBTypes, true, dogColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Dogs().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, dogDBTypes, true, dogPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Dog struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(dogAllColumns, dogPrimaryKeyColumns) {
		fields = dogAllColumns
	} else {
		fields = strmangle.SetComplement(
			dogAllColumns,
			dogPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DogSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}
