// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Accesses", testAccessesUpsert)

	t.Run("Auths", testAuthsUpsert)

	t.Run("RolesUsers", testRolesUsersUpsert)

	t.Run("Sessions", testSessionsUpsert)

	t.Run("TokenPasswords", testTokenPasswordsUpsert)

	t.Run("Users", testUsersUpsert)
}
